apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
  labels:
    app: react
spec:
  replicas: {{ .Values.replicas.react }}
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: kube
          image: "{{ .Values.containerImage.react }}:{{ .Values.commitId }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPorts.react }}