apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-deploy
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log
  template:
    metadata:
      labels:
        app: log
    spec:
      containers:
        - name: kube
          image: gauti019/logger-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3099
