apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
  labels:
    app: react
    helm.sh/chart: '{{ .Values.label }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: kube
          image: gauti019/kube-deploy:87d500f695862c245cc95b842742aaf14abac209
          imagePullPolicy: Always
          ports:
            - containerPort: 3030