apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  type: ClusterIP
  selector:
    app: react
  ports:
    - protocol: TCP
      port: {{ .Values.servicePorts.react }}
      targetPort: {{ .Values.containerPorts.react }}

    # - port: {{ .Values.servicePorts.react }}
    #   targetPort: {{ .Values.containerPorts.react }}  # this is where APPLICATION-PORT goes.
    #   nodePort: 30009
    #   protocol: TCP
    #   name: http
