apiVersion: v1
kind: Service
metadata:
  name: log
spec:
  type: ClusterIP
  selector:
    app: log
  ports:
    - port: 80 # what is it's use
      protocol: TCP
      targetPort: 3099 # this is where APPLICATION-PORT goes.

      # nodePort: 30011
      # protocol: TCP
      # name: http
