apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ingress
  name: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx-ingress
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
