apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  type: LoadBalancer
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030

    # - port: 80
    #   targetPort: 3030      # this is where APPLICATION-PORT goes.
    #   nodePort: 30009
    #   protocol: TCP
    #   name: http
