# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: "Use Node.js 10.x"
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: "Install Dependencies"
        run: npm ci

      - name: "Create Build Frontend"
        run: npm run build

      - name: "setup k8s inside container"
        uses: azure/setup-kubectl@v1
        with:
          version: latest
        id: install

      - name: Build and push to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          repository: gauti019/kube-deploy
          tags: latest

      # - name: "Deploy app"
      #   run: kubectl --kubeconfig kubefiles/config apply -f kubefiles/react-deployment.yaml

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud info

      # - name: Trying out gcloud action
      #   uses: gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project test-1-286907
